### PR TITLE
Added themed icon for android 13

### PR DESCRIPTION
**Pull request by Azure-Helper**
IMG_20220901_203524_546~2

### CODE REVIEW

**Comment by TrianguloY** [comment]
Looks good, thanks! 
My only complaint is the that the new file seems to be identical to the launcher foreground, except for the color. 
Could it be possible to merge them both somehow? 
What happens if you specify the current foreground as the monochrome?

Let me try before merging

**Comment by Azure-Helper** [comment]
> Looks good, thanks! My only complaint is that the new file seems to be identical to the launcher foreground, except for the color. Could it be possible to merge them both somehow? What happens if you specify the current foreground as the monochrome?
> 
> Let me try before merging

Yeah it's possible.

**Comment by TrianguloY** [comment]
Ugh, due to some issues with my computer I'm unable to update this PR. Could you apply this patch? (removes the duplicated file and links the existing one instead).
I'll merge afterwards.

```patch
Index: app/src/main/res/drawable/ic_launcher_monochrome.xml
===================================================================
diff --git a/app/src/main/res/drawable/ic_launcher_monochrome.xml b/app/src/main/res/drawable/ic_launcher_monochrome.xml
deleted file mode 100644
--- a/app/src/main/res/drawable/ic_launcher_monochrome.xml	(revision 681f713242742ee5c4cee84c01847f7a1d2c2617)
+++ /dev/null	(revision 681f713242742ee5c4cee84c01847f7a1d2c2617)
@@ -1,15 +0,0 @@
-<vector xmlns:android="http://schemas.android.com/apk/res/android"
-    android:width="108dp"
-    android:height="108dp"
-    android:viewportWidth="108"
-    android:viewportHeight="108">
-    <group
-        android:scaleX="2.61"
-        android:scaleY="2.61"
-        android:translateX="22.68"
-        android:translateY="22.68">
-        <path
-            android:fillColor="#000"
-            android:pathData="M3.9,12c0,-1.71 1.39,-3.1 3.1,-3.1h4L11,7L7,7c-2.76,0 -5,2.24 -5,5s2.24,5 5,5h4v-1.9L7,15.1c-1.71,0 -3.1,-1.39 -3.1,-3.1zM8,13h8v-2L8,11v2zM17,7h-4v1.9h4c1.71,0 3.1,1.39 3.1,3.1s-1.39,3.1 -3.1,3.1h-4L13,17h4c2.76,0 5,-2.24 5,-5s-2.24,-5 -5,-5z" />
-    </group>
-</vector>
Index: app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml b/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
--- a/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml	(revision 681f713242742ee5c4cee84c01847f7a1d2c2617)
+++ b/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml	(revision a6ca7c56db4aa644dcc994c7d646a9cfbd968afb)
@@ -2,5 +2,5 @@
 <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
     <background android:drawable="@color/ic_launcher_background" />
     <foreground android:drawable="@drawable/ic_launcher_foreground" />
-    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
+    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
 </adaptive-icon>

```

**Comment by Azure-Helper** [comment]
> Ugh, due to some issues with my computer I'm unable to update this PR. Could you apply this patch? (removes the duplicated file and links the existing one instead). I'll merge afterwards.
> 
> ```diff
> Index: app/src/main/res/drawable/ic_launcher_monochrome.xml
> ===================================================================
> diff --git a/app/src/main/res/drawable/ic_launcher_monochrome.xml b/app/src/main/res/drawable/ic_launcher_monochrome.xml
> deleted file mode 100644
> --- a/app/src/main/res/drawable/ic_launcher_monochrome.xml	(revision 681f713242742ee5c4cee84c01847f7a1d2c2617)
> +++ /dev/null	(revision 681f713242742ee5c4cee84c01847f7a1d2c2617)
> @@ -1,15 +0,0 @@
> -<vector xmlns:android="http://schemas.android.com/apk/res/android"
> -    android:width="108dp"
> -    android:height="108dp"
> -    android:viewportWidth="108"
> -    android:viewportHeight="108">
> -    <group
> -        android:scaleX="2.61"
> -        android:scaleY="2.61"
> -        android:translateX="22.68"
> -        android:translateY="22.68">
> -        <path
> -            android:fillColor="#000"
> -            android:pathData="M3.9,12c0,-1.71 1.39,-3.1 3.1,-3.1h4L11,7L7,7c-2.76,0 -5,2.24 -5,5s2.24,5 5,5h4v-1.9L7,15.1c-1.71,0 -3.1,-1.39 -3.1,-3.1zM8,13h8v-2L8,11v2zM17,7h-4v1.9h4c1.71,0 3.1,1.39 3.1,3.1s-1.39,3.1 -3.1,3.1h-4L13,17h4c2.76,0 5,-2.24 5,-5s-2.24,-5 -5,-5z" />
> -    </group>
> -</vector>
> Index: app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml b/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
> --- a/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml	(revision 681f713242742ee5c4cee84c01847f7a1d2c2617)
> +++ b/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml	(revision a6ca7c56db4aa644dcc994c7d646a9cfbd968afb)
> @@ -2,5 +2,5 @@
>  <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
>      <background android:drawable="@color/ic_launcher_background" />
>      <foreground android:drawable="@drawable/ic_launcher_foreground" />
> -    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
> +    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
>  </adaptive-icon>
> ```

Done

**Comment by TrianguloY** [comment]
Perfect, merged!

**Pull request merged**
