### PR TITLE
Update french translation

### PR DESCRIPTION
**Pull request by Ilithy**
To follow the additions made in #27

### CODE REVIEW

**Comment by TrianguloY** [comment]
Oh! Thanks! 
But I'll probably tweak a few things still, so some string may change (not drastically I hope) before the release. I'll wait until everything is ready to allow you to translate the final version, and then I'll merge it.

**Comment by Ilithy** [comment]
Very good, that makes sense

**Comment by TrianguloY** [comment]
Btw, I don't mind if you want to update this PR occasionally, but I'll notify you (here) when the update is ready to be published, don't worry. This update is expected to have quite some features!

**Comment by Ilithy** [comment]
This is great news! I do this to avoid missing things, but if you have to make a lot of changes, I'll make a single point when you tell me, no problem in sight.

**Comment by TrianguloY** [comment]
Finally! after all these years!

Ahem, sorry for taking too long, my time is limited so...
Anyway, I finally finished the spanish translation so now I can confirm the repository is ready to be translated and then I'll upload the new version. I have some other changes in progress but those will go to future versions.

Take your time to update it, don't worry (I took mine). In the meantime I think I'll publish a beta on Play Store to test for common crashes before the full release. (Its a shame F-droid doesn't have a beta feature)

**Comment by Ilithy** [comment]
>Finally! after all these years!

>Ahem, sorry for taking too long, my time is >limited so...
>Anyway, I finally finished the spanish translation >so now I can confirm the repository is ready to >be translated and then I'll upload the new >version. I have some other changes in progress >but those will go to future versions.  


you took the necessary time, it's normal, you don't have to apologize, thank you; I will remain available in the future to update this translation.


>Take your time to update it, don't worry (I took >mine). In the meantime I think I'll publish a beta >on Play Store to test for common crashes before >the full release. (Its a shame F-droid doesn't >have a beta feature)


I'll take care of it, it shouldn't take very long. The beta version is a great idea, and yes, it's downright annoying that Fdroid does not manage a beta channel for apps.

_Thank you for your work on your apps, I hope you will keep the flame alive, even in the middle of a storm <3_

**Comment by Ilithy** [comment]
Normally this should be fine.

I removed the backslash (\) in front of the apostrophes ('), I hope I didn't make a mistake.

If it were possible to integrate the French translation into the beta version, this would allow me to verify that there was no oversight on my part (one is never too careful).

If not, I would do a direct verification of the file, thank you very much.

**Comment by TrianguloY** [comment]
> I removed the backslash () in front of the apostrophes ('), I hope I didn't make a mistake.

That's something I knew from a long time ago but never took the time to really understand it. 
Turns out that special characters need to be escaped, but if you put the whole string between double quotes some of them are not. These includes linebreaks and apostrophes, so the rule is: if you have linebreaks and/or apostrophes either escape them or put the string in double quotes. If not, just write it.
Here are some details, but not very descriptive: https://developer.android.com/guide/topics/resources/string-resource#FormattingAndStyling

> If it were possible to integrate the French translation into the beta version, this would allow me to verify that there was no oversight on my part (one is never too careful).

Sure! this weekend you'll have it.

**Comment by Ilithy** [comment]
Ok it's clear, let me modify the file to correct my erroneous modifications

**Comment by Ilithy** [comment]
@TrianguloY the translation is ready for beta, thanks.

**Review by abyisysfogoso-stack — CHANGES_REQUESTED** [review]
Everyone need cult

**Pull request merged**
