### PR TITLE
Open and share update

### LINKED ISSUE #14: Can´t check URLs from YouTube
Prerequisites:
- Default browser app set to none

Steps to reproduce:
1. Open YT app.
2. Go to any video with links in the description. [E. G.](https://www.youtube.com/watch?v=wSy3kAHtmF8)
3. Click any non-YT link.
4. UrlChecker doesn't show up in the "Complete action using" pop-up dialog.

Note that the URL it gives you is a YT redirection, so any links to social media pages won't give you the option to open it in their app, which can be easily solvable with the ClearURLs module.

The only apps I can get to show up are:
- Brave browser.
- DuckDuckGo browser.
- Kiwi browser.
- Firefox browser.
- Firefox focus browser.
- Tor browser.
- URLSanitizer, which is an app to handle URLs too.

Other apps like "Share to clipboard", "UntrackMe" or "Open Link with" do not show up either.

From what I can see it looks like UrlChecker needs to show up as some kind of browser for this to work.

### PR DESCRIPTION
**Pull request by PabloOQ**
Fix #14 
First commit of the branch, easy fix of the manifest.

[Added Integer preference](https://github.com/TrianguloY/UrlChecker/commit/a49d6d04927196737a79f9d080d9088fc5490ecd)
I didn't reuse long because the item selected on the spinners give an int not long. This should be of use to attach any spinner to a preference, could be useful to choose the language as a preference, or select night mode.

Implemented #39 

Suggested solution for #37
Preset flags feature: There are a number of presets flags to apply to the intent, overriding all previous flags. To make space for the button a dropdown was added, which contains any additional settings of the module that can be modified in the dialog. There are 2 presets at the moment:
- Temporal: Works as the [twitter video 'inside' ](https://github.com/TrianguloY/UrlChecker/issues/37#issuecomment-1205743582). Doesn't always work, depends on the app, it didn't work on Brave for me, but it did on Firefox focus, YT and Twitter for example. 
- New window: Works as the [youtube video 'outside' ](https://github.com/TrianguloY/UrlChecker/issues/37#issuecomment-1205743582)
There are 3 icons added, the `mopen_auto.xml` icon was just copy paste from other icon as I didn't know what it should be. When the feature detects that the intent is the same as one of the presets it will not show the auto icon while rotating the presets in the dialog.

I intentionally added the preset flags feature the last so it can be easily reverted or entirely ditched, as I must admit the solution is somewhat weird. Feel free to remove it if you feel it doesn't fit the app.

Each commit has it's spanish translation too if there was any string added.

### CODE REVIEW

**Comment by TrianguloY** [comment]
A quick glance over the code and everything seems ok, although I'll refactor a couple things as usual.
Nice commits, nice comments, bravo!
Just give me a couple days to correctly review it.

I would have made the #14 fix a separate PR though (it's a different thing). Similar with #39 and #37 but those are related so it's ok to keep them altogether. 
In any case don't worry, no need to separate them now (although I think you can create a branch from that first commit, make a PR for it, and then this one will be automatically updated without it...hmm, you can try if you want).

**Comment by PabloOQ** [comment]
I will keep that in mind for future PRs

> I think you can create a branch from that first commit, make a PR for it, and then this one will be automatically updated without it

[Like this?](https://github.com/PabloOQ/UrlChecker/commits/Fix-manifest)

**Comment by TrianguloY** [comment]
> I will keep that in mind for future PRs

Perfect, also thanks for taking the time to group the commits nicely 👍


> [Like this?](https://github.com/PabloOQ/UrlChecker/commits/Fix-manifest)

I think so. Try creating a PR from that branch!

**Comment by TrianguloY** [comment]
Hmm, it didn't work :/
I guess you should rebase the branch for it to detect the changes? but that can make a lot more problems so better not. It's just a single file, no big issue.

**Comment by PabloOQ** [comment]
I am using the wrong flags on `EXCLUDE_RECENTS`, the purpose of _New window_ is to open it externally which currently does not always do. As you mentioned on #37, I think the flag which should be used is `FLAG_ACTIVITY_NEW_TASK`, I will do more tests on this. Which leads to something I suspected I was doing wrong, using the flags as keys.
Also the icon for `AUTO` is not the correct one. 

> When the feature detects that the intent is the same as one of the presets it will not show the auto icon while rotating the presets in the dialog.

Lastly, I think it would be better if the button has a different color whenever the current option corresponds to the original flags of the intent.

I can fix these issues, but how should I proceed? I can close this PR and split it in 2, the custom tabs buttons and the preset flags, or I can just do the commits in this PR.

**Comment by TrianguloY** [comment]
Wait. I've started working on this PR. I'll let you know later when I have time to write more than a few sentences 😅

**Comment by TrianguloY** [comment]
Ok, lets go.

I started reviewing the changes. The first thing I saw is that, as you said, the preset flags feature is a bit strange. Ideally there should be only 1 flag, or multiple but independent. Also '[FLAG_ACTIVITY_BROUGHT_TO_FRONT](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_BROUGHT_TO_FRONT)' is marked as 'not normally set by application code'.
The icons must also need to be changed (maybe even setting text next to them to clarify), so I decided to skip that commit and only merge the #39 change.
In any case your solution for #47 could be useful in the future (I really like the dropdown with the extra options there), I can save it on a branch in this repository if you want.

As for the #39 feature, as usual I started changing and refactoring code (this is my fault, sorry). Mainly the way the preference is saved because you can either save the enum index or the enum name. With an index you depend on the enum order itself, which can change under some very specific situations. With the name you can't rename the enum values, but at least you can reorder/add/remove new elements if needed. I don't know if there is a better way, but I prefer saving the enum name instead of your index choosing. 
In any case I'm refactoring it so that the 'preference' is the enum itself! So that the code using it works with the enum directly (no matter how it's saved) and the preference class is the one deciding how to save it (it's a better separation of responsibilities, I think). I'm also adding a way to attach a translatable string to any enum value directly, instead of using a separate pair-like class.

Hopefully this afternoon I'll be able to upload it. You don't need to do anything for this, but if you want try to check if the FLAG_ACTIVITY_NEW_TASK is enough for the #39 feature.

<br>

Btw...as I asked Ilithy before: Would you like to become a collaborator? [In your case as a programmer I'll probably ask you to create a PR for any non-obvious change anyway, but your help fixing small bugs or even translating spanish could be useful.]

**Comment by PabloOQ** [comment]
> Also '[FLAG_ACTIVITY_BROUGHT_TO_FRONT](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_BROUGHT_TO_FRONT)' is marked as 'not normally set by application code'.

I just took the flags that twitter uses to mimic the 'temporal' behaviour.

>  Mainly the way the preference is saved because you can either save the enum index or the enum name. With an index you depend on the enum order itself, which can change under some very specific situations. With the name you can't rename the enum values, but at least you can reorder/add/remove new elements if needed. I don't know if there is a better way, but I prefer saving the enum name instead of your index choosing.

That's exactly why I used a key, using the index was a big no, and using the string while better wasn't really a good alternative.

> In any case I'm refactoring it so that the 'preference' is the enum itself! So that the code using it works with the enum directly (no matter how it's saved) and the preference class is the one deciding how to save it (it's a better separation of responsibilities, I think).
That's what I tried at first, but couldn't get it to work, that's when I decided to rely on the key value class. Hopefully you get it to work.

> Btw...as I asked Ilithy before: Would you like to become a collaborator? [In your case as a programmer I'll probably ask you to create a PR for any non-obvious change anyway, but your help fixing small bugs or even translating spanish could be useful.]
I don't mind, in the end is what you are saying, I would still do PRs for features, but I can do translations when needed.

**Comment by TrianguloY** [comment]
It's merged now! (the #39, not the #47). I even added two extra settings: always on (the button is hidden but the ctabs are enabled) and always off (same but with off).

> That's exactly why I used a key, using the index was a big no, and using the string while better wasn't really a good alternative.

I investigated and saw that using an extra integer, exactly what you did, is the correct alternative in almost all cases (turns out that under some conditions the enum values can change, mainly with proguard and obfuscation). With my refactor I think it even looks nicer.

> That's what I tried at first, but couldn't get it to work, that's when I decided to rely on the key value class. Hopefully you get it to work.

I hope so! You can check it and see if you like it.

> I don't mind, in the end is what you are saying, I would still do PRs for features, but I can do translations when needed.

Ok! Just let me prepare a few things first and I'll send you the invitation.

**Comment by TrianguloY** [comment]
I'm closing this PR as it is no longer needed. I keep the extra commit in shelf/PR68 if needed.

**Comment by PabloOQ** [comment]
It's exactly how I wanted to do it! It's a shame I couldn't make it work, I apologize for the inconvenience.

**Comment by TrianguloY** [comment]
I admit it was hard to manage to make it work properly, but I liked how it ended...except for the TranslatableEnum (why on Java you can't extend enums...why...on Kotlin you can...if only Kotlin weren't so badly optimized...).

Anyway, as you probably saw I use this and other free-time projects to allow making interesting and 'innovative' (at least for me) programming things. I had a great time making this, no need to apologize.

I'll even probably use this opportunity to learn about annotationProcessors. Let's see if I can make one!

**Pull request closed without merging**
