### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Ilithy**
(first step) added primary help for translators

### CODE REVIEW

**Comment by Ilithy** [comment]
I don't know if the way I added this will suit you, I'm thinking of doing something more complete (if it remains, I'll probably make it more exhaustive)

**Comment by TrianguloY** [comment]
I would like to setup an automatic action to generate a zip with the translation files directly (like I have in the Click to chat app). There are also public services for translations that I can check (to avoid manual translation of string files).

If you have time and want to, update as you please, if not don't worry.

**Comment by Ilithy** [comment]
>There are also public services for translations that I can check (to avoid manual translation of string files).

I think this technique would be the most viable, and the most practical (once implemented), have you looked at [Weblate](https://weblate.org/)?
seems like a great compromise, and they have a [free plan for FOSS software](https://hosted.weblate.org/accounts/login/?next=/hosting/).

I'll leave what I added (if you don't mind the edits) and once the final solution is in place I'll remove it, when do you think?

**Comment by TrianguloY** [comment]
> have you looked at [Weblate](https://weblate.org/)?

That's exactly the service I have on my TO-DO list to check someday...

**Comment by TrianguloY** [comment]
I added links and a bit more description to translations.
And also made sentences in plural (I'm the main and currently only developer, but who knows in the future). I also like to have general instructions related to a 'team'

Check them if necessary and do an Squash and merge yourself (I want to check what happens when there are multiple authors)

**Comment by Ilithy** [comment]
Please check in return

**Comment by TrianguloY** [comment]
Note: I change some repository settings:
- When doing a Squash-merge with a PR, the commit that is generated (with all those changes) will have the title and description of the PR itself (currently it was auto-generated). You now have easy control of that commit.
- I enabled the 'always suggest updating the pr branch' option. This should mean that now you can easily rebase a branch to 'main' via web (if it doesn't work as expected and it's more confusing I can remove it again)
- Merged branches are now automatically deleted. A button to restore them will be present if needed.

**Pull request merged**
