### PR TITLE
Close on share (for background apps)

### PR DESCRIPTION
**Pull request by PabloOQ**
Implemented #42 
Next step would be to implement a way to look if the share was succesfull or not, this way URLCheck doesn't close if the user unintentionally shares the URL.

### CODE REVIEW

**Comment by TrianguloY** [comment]
Looks good! 
- Ignore the code scanning comment
- I think in the merge you forgot some commits, the "This module can't be disabled" strings should not reappear.
- I'm not sure about it being enabled by default, but I guess it's better this way so ok.
- Are you confident about adding another one for the open? Just the same (calling finish) should be enough?

**Comment by Ilithy** [comment]
_I took the liberty of adding the new string to the FR file, I did not touch anything else_

**Comment by PabloOQ** [comment]
> I think in the merge you forgot some commits, the "This module can't be disabled" strings should not reappear.

Whoops, I was working on an old commit (a month ago or so), and some strings reappeared, thought I cleaned everything.

> Are you confident about adding another one for the open? Just the same (calling finish) should be enough?

Sure! Should I add another preference or reuse the same one?

**Comment by TrianguloY** [comment]
> Sure! Should I add another preference or reuse the same one?

I think it's better to use another

**Comment by Ilithy** [comment]
_The new option is translated into French_

**Comment by Ilithy** [comment]
_The new option is translated into French_

**Comment by ig9000** [comment]
Just now got around to trying this out, works as I hoped it would. Thank you!

**Pull request merged**
