### PR TITLE
Fix #14

### LINKED ISSUE #14: Can´t check URLs from YouTube
Prerequisites:
- Default browser app set to none

Steps to reproduce:
1. Open YT app.
2. Go to any video with links in the description. [E. G.](https://www.youtube.com/watch?v=wSy3kAHtmF8)
3. Click any non-YT link.
4. UrlChecker doesn't show up in the "Complete action using" pop-up dialog.

Note that the URL it gives you is a YT redirection, so any links to social media pages won't give you the option to open it in their app, which can be easily solvable with the ClearURLs module.

The only apps I can get to show up are:
- Brave browser.
- DuckDuckGo browser.
- Kiwi browser.
- Firefox browser.
- Firefox focus browser.
- Tor browser.
- URLSanitizer, which is an app to handle URLs too.

Other apps like "Share to clipboard", "UntrackMe" or "Open Link with" do not show up either.

From what I can see it looks like UrlChecker needs to show up as some kind of browser for this to work.

### PR DESCRIPTION
**Pull request by PabloOQ**

### CODE REVIEW

**Comment by TrianguloY** [comment]
I probably though that by adding no mimetype it would match all, but apparently isn't?

I wonder if adding "*" as mimetype will also work and allow even more intents to work.

In any case it's just a very minor fix that adds an intent, and if you tested it and it solves the bug then perfect!

**Comment by PabloOQ** [comment]
Honestly, the bug itself was very specific, as after setting URLChecker as the browser it worked correctly, but if it wasn't then it wouldn't show up only in the youtube app. I wouldn't look too much into it.

**Comment by Ilithy** [comment]
> I probably though that by adding no mimetype it would match all, but apparently isn't?
> 
> I wonder if adding "*" as mimetype will also work and allow even more intents to work.

I am not totally sure of myself, but there may be a solution to this, I attach an [issue](https://github.com/Kunzisoft/KeePassDX/issues/1211#issuecomment-1218456465) in which the developer @J-jamet seems to have a similar problem, it may help..._(maybe)_

**Comment by TrianguloY** [comment]
I think [this](https://developer.android.com/guide/components/intents-filters#DataTest) is the important part:

By no specifying mimetype some cases don't match, apparently YouTube is one of them.

If another similar issue arises I'll check again, but for now this is a perfectly good solution. 👍

**Pull request merged**
