### PR TITLE
(Proposal) PRIVACY POLICY

### PR DESCRIPTION
**Pull request by Ilithy**
Proposal to add a _(simple)_ privacy policy.

_Can (eventually) be added to the About Url Checker page (show as popup), but that's another story._

### CODE REVIEW

**Comment by TrianguloY** [comment]
Wow, to think that the current privacy policy is this: https://triangularapps.blogspot.com/p/url-checker-privacy-policy.html

Did you used a template or something? It looks very professional (and it may help me in other apps). Three are a few ideas that could be added present in the link above:

- See the suggestion about the automatic feature
- When opening an app the url, and only the url is sent.

**Comment by Ilithy** [comment]
Honestly I started with a privacy policy of an application (Nova video player) and it is adapted to Url checker, I find it simple and leaves no doubt (except this part pointed out by your comment)

thank you for giving me the link to your privacy policy, I had not seen it --'


Indeed, the part on the automation and the sending of the url are important points, I modify, that in my proposal.

You are free to use it as you see fit.

**Comment by Ilithy** [comment]
Isn't this formulation problematic?

"In any case, only the displayed url will be fetched/sent."

Doesn't the scan module send other data? (such as the user's api key), doesn't that conflict?

**Comment by TrianguloY** [comment]
Hmm, the VirusTotal api key is used to authenticate the petition (if it's wrong it just fails). I treated it as a token, but I'm no lawyer so no idea if it's considered a private data, although I guess it is.
I updated the policy, but I'll replace it with this one so don't worry much about it.

**Comment by Ilithy** [comment]
That's fine with me

**Comment by TrianguloY** [comment]
I decided to remove that sentence. The rest of the document is very detailed and I think it's more confusing that not.
But if you think it's better to leave it I have no problem.

I also added links and tweaked a few punctuation

**Comment by Ilithy** [comment]
All your modifications are excellent, with them it seems to me that it covers everything.

**Comment by TrianguloY** [comment]
Merged then! 
Of course it can be updated further if needed.

**Pull request merged**
