### PR TITLE
Assets update action

### PR DESCRIPTION
**Pull request by PabloOQ**
This action updates assets files, currently there is only one asset file, the ClearURLs catalog, but  the action can be easily expanded if more are added ( maybe these issues can benefit from it: #82 #61 #10 #7 ), just copy and paste the ClearURLS catalog step and change the enviroment variables.

I think that even with the built-in catalog updater the app should come bundled with a recent file.

The script **needs** a hash url to confirm a successful download, I thought of removing this resctrition, but I don't like the idea of auto-commiting without some kind of verification. If a source doesn't have a hash to confirm it can be solved by forking the repo and adding an action to automatically sync with main every now and then, after that the action could just generate the hash.

The action won't fail if an asset could not be updated as it is aimed to update more than one file at the same time, these failures include:

- Hash does not match
- Folder does not exist
- The new file hash is the same as the current one
- Download failed

If the PR is merged it's important to keep in mind that the field `on:` is intentionally left out, I leave to you to decide when to run it the action, these are some that I thought could be useful:

- Manually

```
# manually
workflow_dispatch:
```

  - On release, this one would update the file after the release tag, so the file won't be technically updated until the next release
```
 # on releases
 release:
```

- I think actions can be called from other actions, so this can be added in an action that makes the releases (apk and all that) too .

- Weekly

```
 # weekly
 schedule:
   - cron: '0 0 * * Sun'
```

Finally, here are some [tests](https://github.com/PabloOQ/UrlChecker/actions). Because the action does not fail if the asset update fails you would need to enter to the workflow run and check the console log of the steps to see the result.

### CODE REVIEW

**Comment by TrianguloY** [comment]
I must say I love this new action. It now seems obvious but I didn't think of it before! 


There is one thing that could be a bit dangerous: automatic commits.
Ideally the action should create a new branch (unless it already exists), make the commit there, and then create/update a PR for us developers to check and merge. This way we have more control over the changes (and we are notified of them!).

As for the trigger, with the manual merge, a cronjob is the best option (once a week for example). I'm not sure if an action can be triggered when an external repository changes, but it if were possible it would be the best (it will only run when the source repo changes!)


Do you want to try to modify it yourself? If not I'll definitely play with it.

**Comment by TrianguloY** [comment]
In the meantime, I added you as a collaborator, feel free to join or ignore it.

If you decide to join just please continue creating PRs for normal and big changes. Small modifications or even bugfixes are ok, although I wouldn't mind a PR if you prefer.

**Comment by PabloOQ** [comment]
> Ideally the action should create a new branch (unless it already exists), make the commit there, and then create/update a PR for us developers to check and merge.
Do you want to try to modify it yourself?

I can change it, shouldn't be too hard.

>  I'm not sure if an action can be triggered when an external repository changes, but it if were possible it would be the best (it will only run when the source repo changes!)

If this is possible, there should be a cooldown or a check timestamp to avoid more than one PR  on the same day, which I think should be more problematic. [On June 29, 9 commits were made on the ClearURLs repo](https://github.com/ClearURLs/Rules/commits/master) . Even then, each commit would trigger a workflow run. I don't think it is possible to make these checks before the workflow run. I will look into it but I don't expect much.

> In the meantime, I added you as a collaborator, feel free to join or ignore it.
If you decide to join just please continue creating PRs for normal and big changes.

Thanks. Will do!

**Comment by TrianguloY** [comment]
> If this is possible, there should be a cooldown or a check timestamp to avoid more than one PR  on the same day, which I think should be more problematic. 

Ideally the script should reuse any active pr if it exists, by committing to the branch. This can be hard though, and as of now the weekly run is enough, so don't worry if you can't find how to do it.

The script could do something like this:

1) check if the custom branch exists, checkout it if it does, create if doesn't
2) Download the new file, then check the hash.
3) if the hash doesn't match, revert the file, if it does create a commit with the info and that change
4) repeat steps 2-3 with each file (currently only 1)
5) if there are new commits, push them
6) if something was pushed, and a pr does not exists, create one

Something like that may work, perhaps there is an easier way though

**Comment by PabloOQ** [comment]
That should be it.
I swapped steps 4 and 5. Also if something fails in step 3 github will abort it, this will avoid the commit and push.

Step 6: I did try to check if there already was a PR, but it is not needed, a head can't have more than one PR pointing to the same base, which makes sense. Because of that the command used in the action fails (the step too) when trying to do a PR if there's already one, however the commits of the assets are pushed before this step so the PR will have them. This also makes the workflow be shown as failed in the actions tab.

The branch does not auto delete after the PR is closed, I think this can't be done here, but it shouldn't be a problem, as the only  files that are modified are the assets.

[Here is the action working.](https://github.com/PabloOQ/UrlChecker/pull/1) There are commits from this branch too because the workflow is executed on top of the changes made in this branch.

To make it work I had to change the settings of my fork `Settings->Actions->General` at the end there's an option to let actions create PRs.

Finally thanks to @Chgv99 who helped me test if the action could cascade into forks making them do PRs to `origin/master`. It does not.

**Comment by TrianguloY** [comment]
> That should be it. I swapped steps 4 and 5. Also if something fails in step 3 github will abort it, this will avoid the commit and push.

Perfect, A commit for each file is even better.

> Step 6: I did try to check if there already was a PR, but it is not needed, a head can't have more than one PR pointing to the same base, which makes sense. Because of that the command used in the action fails (the step too) when trying to do a PR if there's already one, however the commits of the assets are pushed before this step so the PR will have them. This also makes the workflow be shown as failed in the actions tab.

It would be better to detect this situation to avoid failing a pr in this situation (so you can be sure that if the action failed it was for an unexpected reason), it's not really important though, it would probably never happen.

> The branch does not auto delete after the PR is closed, I think this can't be done here, but it shouldn't be a problem, as the only files that are modified are the assets.

That's something that the repository can be configured as, and I think it's set as such. When merging it should be auto-deleted. If not I guess the action will simple start from the old one, which as you said is not important since only the assets are updated. If really necessary I guess it can make a rebase first (which will do nothing if rebased already).
 
> To make it work I had to change the settings of my fork `Settings->Actions->General` at the end there's an option to let actions create PRs.

Already enabled :+1: 

> Finally thanks to @Chgv99 who helped me test if the action could cascade into forks making them do PRs to `origin/master`. It does not.

Thanks both of you for the extra check!

---

I have just one more question: why do you use a temporal folder instead of simply downloading it directly? It runs under git, so you should be able to revert it to the latest commit version on error. Not really important, just wondering.

**Comment by PabloOQ** [comment]
> It would be better to detect this situation to avoid failing a pr in this situation (so you can be sure that if the action failed it was for an unexpected reason), it's not really important though, it would probably never happen.

I did try to find if there was a PR already, it should be possible with `gh pr list` , but I couldn't make it work. I am probably misunderstanding the sintaxis of `--base` and `--head`. Still, to the best of my knowledge I tried every combination ( `origin`, `main`, `master`, `assets-update-action`, `origin/assets-update-action` , `origin:assets-update-action` ,... ) and it wouldn't work. And with the [search query syntax (`--search`)](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-branch-name) if I searched for `assets-update-action` it would detect `assets-update-action-2` too, which will probably never happen, but I rather not do the check than do it wrong. Because this would only fix how it's shown in the actions tab I thought it wasn't that bad. Feel free to give it a shot if you want.

> I have just one more question: why do you use a temporal folder instead of simply downloading it directly?

Honestly I didn't thought of reverting changes. At first I was using [git auto commit](https://github.com/stefanzweifel/git-auto-commit-action), which adds and commits everything, except hidden folders if I remember correctly. I was also downloading things on the root folder and if the hash failed I would remove them, if the hash matched I would move them to their respectives folder. With that in mind if an asset path was the root folder itself and the hash failed it would remove the file and then commit it. To solve that I would just download things in the hidden folder.

I decided to ditch git auto commit because adding everything is a bad praxis, also I wanted to avoid using actions that weren't from github.

**Pull request merged**
