### PR TITLE
Update french

### PR DESCRIPTION
**Pull request by Ilithy**
- strings file updated
- changelogs updated

### CODE REVIEW

**Comment by TrianguloY** [comment]
Ugh, I was writing a message and for some reason the 'enter' key merged it, sorry.

If you wanted to make more changes feel free to create a new one.

(I need to be more careful with Github Web...)

**Comment by TrianguloY** [comment]
Wait...AH you merged it! That's why it suddenly changed to merged, I though I had pressed the button myself.

Next time remember to put yourself as "asignee" so that I know you are going to take care of the PR yourself 👍

**Comment by Ilithy** [comment]
Oh sorry, I'll do it next time, if would you rather do it? I will understand easily

**Comment by TrianguloY** [comment]
Don't worry if you forget, it's not a big deal, it just helps me quickly identify the PRs you are working on.

> if would you rather do it I will understand easily

Sorry, I don't understand this sentence. You mean an example?
This is what I'm referring to

**Pull request merged**
