### PR TITLE
Added Log module to description

### PR DESCRIPTION
**Pull request by Ilithy**
- Adding the Log Module to the English and French description file. _(Slightly lightened version)_

### CODE REVIEW

**Comment by TrianguloY** [comment]
Ah! You beat me to it! 
I want to update the store texts too (most other modules are out of date too) so I'll try to merge both suggestions.

**Comment by Ilithy** [comment]
This was not intended :), I love this module, so I couldn't resist for long.
It's more for fun so if my PR doesn't fit in the text or in the form, don't hesitate to close it (especially if you want to make important changes to the descriptions).

Friendly

**Comment by TrianguloY** [comment]
Oh, you closed it?
I (finally) made the modifications: https://github.com/TrianguloY/UrlChecker/commit/9a29641222e2b66b15659c19392e5b2133869694, feel free to change it if you think it can be improved!

**Comment by Ilithy** [comment]
Yes, by mistake sorry, I look at your work, and I make the changes on the French translation quickly, my apologies.
_(I will eventually propose you some modifications, but very eventually)_

Thank you

**Pull request closed without merging**
