### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by Sevichecc**

### CODE REVIEW

**Comment by TrianguloY** [comment]
Apparently the name of the folder needs to have an extra 'r' (Android is very strange with locales)

Let's see if it works now...

**Comment by Ilithy** [comment]
Sorry for the wrong information, indeed @TrianguloY is right, the folder name should be `values-zh-rCN`

**Comment by TrianguloY** [comment]
Fixed!

Let me review it a bit and I'll merge it (just to make sure the translation is more or less expected and there is no hidden messages).

Thanks!

**Comment by Sevichecc** [comment]
Sorry for the extra command, I use VS Code (but with Neovim extendsion 🤣

**Comment by TrianguloY** [comment]
Apologies for the delay. Everything seems fine. Merged!

**Pull request merged**
