### PR TITLE
Update french file

### PR DESCRIPTION
**Pull request by Ilithy**
* Add new lines (to follow additions)
* Improvement, clarification and small corrections.

### CODE REVIEW

**Comment by TrianguloY** [comment]
Great.
But I'm going to try something. Instead of merging each change, which also requires you to update your branch with the latest merge, I'm going to leave this PR open until I build the next version. 

This way you can update this directly and as much as needed without any obstacle (hopefully) and then before building the version, after the changelog translation, I'll merge it.

If this happens to be worst, we'll be back to the usual method though.

**Comment by Ilithy** [comment]
I was following your methodology, no problem in sight.
If you prefer next time I will wait for you to modify the changelogs (which will serve me as a starting flag) to update the french files.

**Comment by TrianguloY** [comment]
The "write small commits"? That's for code, but I understand the confusion.
You can wait for the changelog or update from time to time, as you wish.

**Comment by TrianguloY** [comment]
v2.6 is ready to translate!

**Comment by Ilithy** [comment]
It's done, thank you 👍

**Pull request merged**
