### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by 404potato**
I translated  `strings.xml`, `title.txt`, `short-description.txt`, `full-description.txt`.  
Thank you for your great app :heart_eyes:   
I use it as my default browser!

### CODE REVIEW

**Comment by TrianguloY** [comment]
Thanks for the translation! Let us review it and we'll merge it.



> https://github.com/TrianguloY/UrlChecker/blob/2889c0aa832cec03a51e9183c625a0b81e3fe2e1/CONTRIBUTING.md?plain=1#L19
> 
> > ./app/src/main/res-{locale}/values/
> 
> BTW, I think the translated `strings.xml` would normally be stored in `./app/src/main/res/values-{locale}/`?

Oops, good catch! I'll fix it now.

**Comment by TrianguloY** [comment]
The string mOpen_ctabsSetting was renamed to mOpen_ctabs, the build fails for this reason. This needs to be fixed.

There are other recent new string not present in your translation, this is not required for the build to succeed: https://github.com/TrianguloY/UrlChecker/compare/0787befbe7866b293b0820f11df8c2e215a781a9...master#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103

**Comment by TrianguloY** [comment]
Works now, thanks!
Merged!

Btw: As a translator I'll add your name to the list of translators for credit: The GitHub name is  **404potato** so I'll use that, but if you want me to use another one (or even not be credited at all) just say so.

**Comment by Ilithy** [comment]
Hi @404potato
Sorry to address you in such a cavalier way, but I noticed that you have participated in several projects, if you don't mind, your help in translating an excellent android application would be very appreciated, it is [Translate You](https://github.com/Bnyro/TranslateYou)
In any case, my apologies for the inconvenience _(and the off topic)_

**Pull request merged**
