### PR TITLE
Readme rework

### PR DESCRIPTION
**Pull request by Ilithy**
-  ~~I have placed your header, until modified (if you like what I will offer you as a replacement).~~

- I haven't added dynamic badges yet (I like it a lot), they require additional files (build.yalm for example), I'm not very strong in code (if you want to make fun of it, fire ;-)), and I don't want to do stupid stupidity, so no indeed, there isn't any dynamics, not yet... ^_°

- Old screenshots have been replaced in their specific folders.

- the art/ folder has disappeared in the bermuda triangle.

- I centered all this a little, for ease of readability (and especially to follow your comment)

- I have totally hidden the links in text versions, but have left them, for the moment (to discuss)

### CODE REVIEW

**Comment by Ilithy** [comment]
I have modified the header with a _(different)_ proposal, feel free to be totally honest, I will change as much as necessary.

**Comment by TrianguloY** [comment]
I renamed the files to avoid duplicates (you can access them on the github log in any case). I also used relative links so that they get the files from the local branch.

**Comment by TrianguloY** [comment]
I added some 'dynamic' badges. They don't require any code at all! I also removed those with information that can be viewed from the main github page too.

**Comment by TrianguloY** [comment]
> I have modified the header with a _(different)_ proposal, feel free to be totally honest, I will change as much as necessary.
> 
> The image is under a free license, just requiring a simple attribution (as long as it is not printed and/or used for profit), if you checked this, here is the license file (be careful, the attribution requests of this file are for a physical print use): https://drive.proton.me/urls/QDS66G2NM0#Smeiaj9WowVw Designer name: royyimzy25414 File link: https://www.vecteezy.com/vector-art/6826888-global-network-connection-world-map-point-and-line-composition-concept-of-global-business-vector-illustration
> 
> [Edit] Image size is 1024px by 500px And less than 500ko.

Hmm, to be honest I prefer the previous background, although this one is nice too. The text/icon still blends with it though (sorry for being too repetitive). Maybe I can...

**Comment by TrianguloY** [comment]
What about this one?
featured

It's edited from a free domain one, so no attribution required: https://www.maxpixel.net/Digital-Network-Internet-Communication-Connections-3537400

**Comment by Ilithy** [comment]
Yes is really great!
More readable than my versions,

Sorry I didn't have the time today to test other designs

**Comment by TrianguloY** [comment]
I think this PR is now ready to merge, can still be improved in the future if needed. 
If you agree, mark it as ready (remove the 'draft' property). If you still want to make more changes just keep it.

**Comment by Ilithy** [comment]
I agree, as you say, it will be time later to make small changes, thanks.

**Pull request merged**
